### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by mjsisley** [zeit/micro-cluster#22]
Thank you for you work on this!

I'm using the latest `micro` and `micro-dev` and those work great. 
However, when attempting to curl the same route with micro-cluster, I get the following error:

```
TypeError: fn is not a function
    at resolve (/XXX/node_modules/micro-cluster/node_modules/micro/lib/index.js:96:34)
    at Promise (<anonymous>)
    at Function.exports.run (/XXX/node_modules/micro-cluster/node_modules/micro/lib/index.js:96:3)
    at Server.server (/XXX/node_modules/micro-cluster/node_modules/micro/lib/index.js:12:50)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
Internal Server Error⏎
```
Any ideas on what could be causing this?

**Comment by kjullien** [comment]
Getting the same error :
```
TypeError: fn is not a function
    at resolve (/Users/user/.config/yarn/global/node_modules/micro/lib/index.js:96:34)
    at new Promise (<anonymous>)
    at Function.exports.run (/Users/user/.config/yarn/global/node_modules/micro/lib/index.js:96:3)
    at Server.server (/Users/user/.config/yarn/global/node_modules/micro/lib/index.js:12:50)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:600:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

steps to reproduce : copy & paste the code in the readme, create an index and a woot with sample return.

it appears to have something to do with the micro lib itself, more precisely this part:
```
exports.run = (req, res, fn) =>
  new Promise(resolve => resolve(fn(req, res)))
    .then(val => {
      if (val === null) {
        send(res, 204, null)
        return
      }

      // Send value if it is not undefined, otherwise assume res.end
      // will be called later
      if (undefined !== val) {
        send(res, res.statusCode || 200, val)
      }
    })
    .catch(err => sendError(req, res, err))
```

It would be great to have a fix, as in this state `micro-cluster` is unusable (literally) for me as of now.

Also same with npm instead of yarn :
```
TypeError: fn is not a function
    at resolve (/Users/user/Projects/micro-service-a-la-con/node_modules/micro-cluster/node_modules/micro/lib/index.js:96:34)
    at new Promise (<anonymous>)
    at Function.exports.run (/Users/user/Projects/micro-service-a-la-con/node_modules/micro-cluster/node_modules/micro/lib/index.js:96:3)
    at Server.server (/Users/user/Projects/micro-service-a-la-con/node_modules/micro-cluster/node_modules/micro/lib/index.js:12:50)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:600:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```
